# Model Definitions - NO API KEYS HERE, ONLY MODEL SPECS
models:
  chat:
    qwen3-30b-a3b:
      provider: openrouter
      model_id: "openrouter/qwen/qwen3-30b-a3b"
      display_name: "Qwen 3 30B A3B"
      temperature: 0.7
      max_tokens: 8000
      context_window: 128000
    
    qwen3-32b:
      provider: openrouter
      model_id: "openrouter/qwen/qwen3-32b"
      display_name: "Qwen 3 32B"
      temperature: 0.7
      max_tokens: 8000
      context_window: 128000
    
    qwen3-32b-reasoning:
      provider: openrouter
      model_id: "openrouter/qwen/qwen3-32b"
      display_name: "Qwen 3 32B (Reasoning)"
      temperature: 0.6
      top_p: 0.95
      top_k: 20
      min_p: 0
      max_tokens: 8000
      context_window: 128000
      enable_thinking: true
    
    qwen3-30b-reasoning:
      provider: openrouter
      model_id: "openrouter/qwen/qwen3-30b-a3b"
      display_name: "Qwen 3 30B A3B (Reasoning)"
      temperature: 0.6
      top_p: 0.95
      top_k: 20
      min_p: 0
      max_tokens: 8000
      context_window: 128000
      enable_thinking: true
    
  
  embedding:
    qwen3-embed:
      provider: deepinfra
      model_id: "Qwen/Qwen3-Embedding-8B"
      display_name: "Qwen 3 Embedding"
      dimensions: 4096

# Provider Base URLs - NO API KEYS HERE
providers:
  openrouter:
    base_url: "https://openrouter.ai/api/v1"
    api_key_env: "OPENROUTER_API_KEY"
  
  deepinfra:
    base_url: "https://api.deepinfra.com/v1/openai"
    api_key_env: "DEEPINFRA_API_KEY"
  
